### ISSUE TITLE
Build Failing for master branch

### ISSUE THREAD

**Issue by ahirani** [JabbR/JabbR#987] opened 2013-09-15 18:31 UTC
Can't not source the Nuget packages for Microsoft.Owin.*

**Comment by cmaish** [comment] 2013-09-18 01:28
The underlying cause for this is that we are using the aspnet webstack nightlies which are only kept online for a short time.  We've updated to the latest nightlies, so the build should work again, but if we don't keep updating the signalr/owin version every few weeks, we will lose the ability to build from scratch again.

**Comment by davidfowl** [comment] 2013-09-18 02:24
Yeah, I hate this shit... >_<. Need to move away from nightlies when 2.0 is released.

**Comment by ahirani** [comment] 2013-09-18 07:10
Cheers Chris..

Understand your dilemma but on a positive note you are forced to always use
the latest version which hopefully should be more stable.

Will pull down master and have a look..

**Comment by ahirani** [comment] 2013-09-18 07:42
Hey guys,

Still having issues building from master.

Can you try clean you packages folder then rebuild, should see what I get.

Thanks,

Neil

**Comment by davidfowl** [comment] 2013-09-18 07:42
The issue isn't fixed in master. The fact that this bug is still open means we didnt fix anything.

**Comment by davidfowl** [comment] 2013-12-01 10:06
Fixed

**Closed as completed by davidfowl** 2013-12-01 10:06 UTC
Labels: bug
