### ISSUE TITLE
Date (month, year, day) above the time on day transitions do not work when scrolling to load history.

### ISSUE THREAD

**Issue by robertwesterlund** [JabbR/JabbR#466] opened 2012-05-13 06:17 UTC
https://github.com/davidfowl/JabbR/issues/178 introduced date headers. These do not seem to work correctly when scrolling up to load message history.

Repro: 
1) Enter a room with many messages
2) Scroll up to make it load more messages
3) Keep scrolling up until you find a place where time switches from AM back to PM. Between these messages there should be a date header, but no such thing is there to be found.

**Comment by samandmoore** [comment] 2012-05-14 22:07
found the root cause:

loading the backscroll uses prependChatMessages https://github.com/davidfowl/JabbR/blob/master/JabbR/Chat.ui.js#L1223 and not addChatMessage... just need to fix that up.

**Comment by davidfowl** [comment] 2012-05-14 23:08
@samandmoore assigning to you.

**Comment by samandmoore** [comment] 2012-05-14 23:18
k, I'm going to try to clean things up a bit

**Comment by samandmoore** [comment] 2012-05-15 02:32
fixed. need to clean up some of the "addMessage", "addChatMessage", "addMessageBeforeTarget" crap later.

**Closed as completed by samandmoore** 2012-05-15 02:32 UTC
Labels: bug
