### ISSUE TITLE
Provide search over message text

### ISSUE THREAD

**Issue by loudej** [JabbR/JabbR#391] opened 2012-02-24 18:41 UTC
Something like the traditional magnifying glass textbox at the top of the page? Search as you type in "rooms you're in" and "all rooms" would be ideal. Lucene might be a great tool for that.

A sidebar with hits on room names and user names might also be nice.

**Comment by davidfowl** [comment] 2012-03-01 08:22
Like this but need to think through the ui.

**Comment by davidfowl** [comment] 2012-05-13 11:23
Dupe of #105

**Closed as completed by davidfowl** 2012-05-13 11:23 UTC
Labels: feature
