### ISSUE TITLE
When external content is added, scrolling behavior and resizing content doesn't work properly

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#94] opened 2011-11-28 12:53 UTC
When an external url brings in content from a content provider, we sometimes scroll and re-size the content before it comes in (since we don't know when the browser has fully loaded the content).

**Comment by kiliman** [comment] 2011-11-30 13:23
I'm not seeing this anymore now that we've gone to the CSS layout. If you can't reproduce, we can close this issue.

**Closed as completed** 2011-11-30 16:28 UTC
Labels: bug
