### ISSUE TITLE
Tabs obscure room note when wrapped

### ISSUE THREAD

**Issue by jmkelly** [JabbR/JabbR#919] opened 2013-07-01 04:32 UTC
In the new UI, when you have a large number of rooms open, once they wrap onto a second line the room note is partially obscured. Not sure how you would want to handle this, or even in fact if this is a real problem.

![image](https://f.cloud.github.com/assets/124026/728469/c80dd53c-e206-11e2-9cbb-35404bc521f9.png)

**Comment by davidfowl** [comment] 2013-07-01 05:57
dupe of #138

**Closed as completed by davidfowl** 2013-07-01 05:57 UTC
